// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Stoqa.OrderCatalog.Infraestrutura.ORM.Context;

#nullable disable

namespace Stoqa.OrderCatalog.Infraestrutura.ORM.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20250312194409_Initial_migration")]
    partial class Initial_migration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Stoqa.OrderCatalog.Domain.Entities.Orders", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasColumnName("code")
                        .HasColumnOrder(2);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("createDate")
                        .HasColumnOrder(3);

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint")
                        .HasColumnName("status")
                        .HasColumnOrder(4);

                    b.HasKey("Id");

                    b.ToTable("Orders", "Stoqa");
                });

            modelBuilder.Entity("Stoqa.OrderCatalog.Domain.Entities.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit")
                        .HasColumnName("active")
                        .HasColumnOrder(5);

                    b.Property<string>("Code")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("code")
                        .HasColumnOrder(4);

                    b.Property<string>("Description")
                        .HasColumnType("varchar(150)")
                        .HasColumnName("description")
                        .HasColumnOrder(6);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasColumnName("name")
                        .HasColumnOrder(2);

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("price")
                        .HasColumnOrder(3);

                    b.HasKey("Id");

                    b.ToTable("Product", "Stoqa");
                });

            modelBuilder.Entity("Stoqa.OrderCatalog.Domain.Entities.ProductOrder", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint")
                        .HasColumnName("order_id")
                        .HasColumnOrder(2);

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint")
                        .HasColumnName("product_id")
                        .HasColumnOrder(3);

                    b.Property<int>("QuantityOrdered")
                        .HasColumnType("int")
                        .HasColumnName("quantity_ordered")
                        .HasColumnOrder(4);

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId")
                        .IsUnique();

                    b.ToTable("ProductOrder", "Stoqa");
                });

            modelBuilder.Entity("Stoqa.OrderCatalog.Domain.Entities.Return", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Approved")
                        .HasColumnType("bit")
                        .HasColumnName("approved")
                        .HasColumnOrder(3);

                    b.Property<string>("Code")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("code")
                        .HasColumnOrder(4);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime")
                        .HasColumnName("createDate")
                        .HasColumnOrder(5);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(250)")
                        .HasColumnName("description")
                        .HasColumnOrder(2);

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint")
                        .HasColumnName("orderId")
                        .HasColumnOrder(1);

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.ToTable("Return", "Stoqa");
                });

            modelBuilder.Entity("Stoqa.OrderCatalog.Domain.Entities.Sale", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint");

                    b.Property<string>("Invoice")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("invoice")
                        .HasColumnOrder(2);

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint")
                        .HasColumnName("orderId")
                        .HasColumnOrder(5);

                    b.Property<bool>("Shipping")
                        .HasColumnType("bit")
                        .HasColumnName("shipping")
                        .HasColumnOrder(4);

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("value")
                        .HasColumnOrder(3);

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.ToTable("Sale", "Stoqa");
                });

            modelBuilder.Entity("Stoqa.OrderCatalog.Domain.Entities.Transport", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Freight")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("freight")
                        .HasColumnOrder(3);

                    b.Property<decimal>("StandardQuote")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("standardQuote")
                        .HasColumnOrder(5);

                    b.Property<string>("TrackingCode")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("trackingCode")
                        .HasColumnOrder(4);

                    b.Property<byte>("TransportType")
                        .HasColumnType("tinyint")
                        .HasColumnName("transportType")
                        .HasColumnOrder(2);

                    b.HasKey("Id");

                    b.ToTable("Transport", "Stoqa");
                });

            modelBuilder.Entity("Stoqa.OrderCatalog.Domain.Entities.ProductOrder", b =>
                {
                    b.HasOne("Stoqa.OrderCatalog.Domain.Entities.Orders", null)
                        .WithMany("ProductOrders")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Stoqa.OrderCatalog.Domain.Entities.Product", "Product")
                        .WithOne()
                        .HasForeignKey("Stoqa.OrderCatalog.Domain.Entities.ProductOrder", "ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Stoqa.OrderCatalog.Domain.Entities.Return", b =>
                {
                    b.HasOne("Stoqa.OrderCatalog.Domain.Entities.Orders", null)
                        .WithOne("Return")
                        .HasForeignKey("Stoqa.OrderCatalog.Domain.Entities.Return", "OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Stoqa.OrderCatalog.Domain.Entities.Transport", "Transport")
                        .WithOne()
                        .HasForeignKey("Stoqa.OrderCatalog.Domain.Entities.Return", "OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Transport");
                });

            modelBuilder.Entity("Stoqa.OrderCatalog.Domain.Entities.Sale", b =>
                {
                    b.HasOne("Stoqa.OrderCatalog.Domain.Entities.Orders", null)
                        .WithOne("Sale")
                        .HasForeignKey("Stoqa.OrderCatalog.Domain.Entities.Sale", "OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Stoqa.OrderCatalog.Domain.Entities.Transport", "Transport")
                        .WithOne()
                        .HasForeignKey("Stoqa.OrderCatalog.Domain.Entities.Sale", "OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Transport");
                });

            modelBuilder.Entity("Stoqa.OrderCatalog.Domain.Entities.Orders", b =>
                {
                    b.Navigation("ProductOrders");

                    b.Navigation("Return");

                    b.Navigation("Sale");
                });
#pragma warning restore 612, 618
        }
    }
}
